# image will be published to ghcr.io/<user>/<name>
name: blue-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # C Development Tools and Libraries
      - autoconf
      - automake
      - binutils
      - bison
      - flex
      - gcc
      - gcc-c++
      - gdb
      - glibc-devel
      - libtool
      - make
      - pkgconf
      - strace

      # Python build dependencies
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - xz
      - xz-devel
      - libffi-devel
      - findutils
      - tk-devel

      # Other build dependencies
      - libyaml-devel
      - readline-devel
      - gdbm-devel
      - ncurses-devel
      - rlwrap

      # Virtualization
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-manager
      - virt-viewer
      - guestfs-tools
      - python3-libguestfs
      - virt-top

      # Container Management
      - podman
      - buildah
      - flatpak
      - flatpak-builder
      - skopeo
      - toolbox

      - bootc
      - firewall-config
      - fuse-encfs
      - hplip
      - ifuse
      - mesa-libGLU
      - python3-pip
      - rclone
      - samba
      - tailscale
      - tmux
      - wl-clipboard

      - skanpage
      - libadwaita-qt5
      - libadwaita-qt6
      - kde-runtime-docs
      - kdenetwork-filesharing
      - kdeplasma-addons
      - kdialog
      - plasma-wallpapers-dynamic

      - adobe-source-code-pro-fonts
      - code
      - libvirt
      - podman-compose
      - qemu
      - ydotool

      - steam-devices
      - distrobox
      - git
      - stow
      - vim-default-editor
      - openrgb
      - gh
      - tlp
      - powertop
      - ripgrep
      - fzf
      - direnv
      - variety

      # - micro
      # - starship
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - nano-default-editor

  - type: akmods
    install:
      - xone

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - com.bitwarden.desktop
        - com.borgbase.Vorta
        - com.discordapp.Discord
        - com.github.tchx84.Flatseal
        - com.google.Chrome
        - com.valvesoftware.Steam
        - com.vivaldi.Vivaldi
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - org.kde.gwenview
        - org.kde.kcalc
        - org.kde.kdenlive
        - org.kde.krita
        - org.kde.okular
        - org.libreoffice.LibreOffice
        - org.qbittorrent.qBittorrent
        - org.videolan.VLC
        - sh.cider.Cider
        - com.heroicgameslauncher.hgl
        - io.github.unknownskl.greenlight
        - org.fedoraproject.MediaWriter
        - org.kde.filelight
        - io.github.flattool.Warehouse
        - org.gnome.Boxes
        - org.kde.kcolorchooser
        - org.godotengine.Godot
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: brew
    brew-analytics: false

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - Ubuntu
      google-fonts:
        - Roboto
        - Open Sans

  - type: chezmoi
    repository: https://github.com/jeffmarder/dotfiles
    all-users: false
    file-conflict-policy: replace

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

